//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 04/04/2017 22:01:38
namespace TFG
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Worm.3ds </summary>
                public const string Worm_3ds = "Content/Assets/Models/Worm.3ds";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Eyes.jpg </summary>
                public const string Eyes_jpg = "Content/Assets/Textures/Eyes.jpg";
                
                /// <summary> Path to Content/Assets/Textures/pl2289146-families_baroque_hdf_waterproof_7mm_laminate_flooring_with_wooden_material.jpg </summary>
                public const string pl2289146_families_baroque_hdf_waterproof_7mm_laminate_flooring_with_wooden_material_jpg = "Content/Assets/Textures/pl2289146-families_baroque_hdf_waterproof_7mm_laminate_fl" +
                    "ooring_with_wooden_material.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Teeth.jpg </summary>
                public const string Teeth_jpg = "Content/Assets/Textures/Teeth.jpg";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Body.wmat </summary>
                public const string Body = "Content/Assets/Materials/Body.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EYE.wmat </summary>
                public const string EYE = "Content/Assets/Materials/EYE.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
