//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 28/05/2017 11:59:31
namespace TFG
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Tombstone_RIP_obj.obj </summary>
                public const string Tombstone_RIP_obj_obj = "Content/Assets/Models/Tombstone_RIP_obj.obj";
                
                /// <summary> Path to Content/Assets/Models/Worm.3ds </summary>
                public const string Worm_3ds = "Content/Assets/Models/Worm.3ds";
                
                /// <summary> Path to Content/Assets/Models/worm_Enemy.3DS </summary>
                public const string worm_Enemy_3DS = "Content/Assets/Models/worm_Enemy.3DS";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/akis.jpg </summary>
                public const string akis_jpg = "Content/Assets/Textures/akis.jpg";
                
                /// <summary> Path to Content/Assets/Textures/button.png </summary>
                public const string button_png = "Content/Assets/Textures/button.png";
                
                /// <summary> Path to Content/Assets/Textures/buttonPress.jpg </summary>
                public const string buttonPress_jpg = "Content/Assets/Textures/buttonPress.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Eyes.jpg </summary>
                public const string Eyes_jpg = "Content/Assets/Textures/Eyes.jpg";
                
                /// <summary> Path to Content/Assets/Textures/grass.jpg </summary>
                public const string grass_jpg = "Content/Assets/Textures/grass.jpg";
                
                /// <summary> Path to Content/Assets/Textures/ground.jpg </summary>
                public const string ground_jpg = "Content/Assets/Textures/ground.jpg";
                
                /// <summary> Path to Content/Assets/Textures/pl2289146-families_baroque_hdf_waterproof_7mm_laminate_flooring_with_wooden_material.jpg </summary>
                public const string pl2289146_families_baroque_hdf_waterproof_7mm_laminate_flooring_with_wooden_material_jpg = "Content/Assets/Textures/pl2289146-families_baroque_hdf_waterproof_7mm_laminate_fl" +
                    "ooring_with_wooden_material.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Standard_D.jpg </summary>
                public const string Standard_D_jpg = "Content/Assets/Textures/Standard_D.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Standard_N.jpg </summary>
                public const string Standard_N_jpg = "Content/Assets/Textures/Standard_N.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Standard_S.jpg </summary>
                public const string Standard_S_jpg = "Content/Assets/Textures/Standard_S.jpg";
                
                /// <summary> Path to Content/Assets/Textures/Teeth.jpg </summary>
                public const string Teeth_jpg = "Content/Assets/Textures/Teeth.jpg";
                
                /// <summary> Path to Content/Assets/Textures/textures.rar </summary>
                public const string textures_rar = "Content/Assets/Textures/textures.rar";
                
                /// <summary> Path to Content/Assets/Textures/Thumbs.db </summary>
                public const string Thumbs_db = "Content/Assets/Textures/Thumbs.db";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Body.wmat </summary>
                public const string Body = "Content/Assets/Materials/Body.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Box.wmat </summary>
                public const string Box = "Content/Assets/Materials/Box.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EnemyBody.wmat </summary>
                public const string EnemyBody = "Content/Assets/Materials/EnemyBody.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EYE.wmat </summary>
                public const string EYE = "Content/Assets/Materials/EYE.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EyeEnemy.wmat </summary>
                public const string EyeEnemy = "Content/Assets/Materials/EyeEnemy.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Ground.wmat </summary>
                public const string Ground = "Content/Assets/Materials/Ground.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TombstoneMaterial.wmat </summary>
                public const string TombstoneMaterial = "Content/Assets/Materials/TombstoneMaterial.wmat";
            }
            
            public sealed class Prefast
            {
                
                /// <summary> Path to Content/Assets/Prefast/Enemy.wpref </summary>
                public const string Enemy = "Content/Assets/Prefast/Enemy.wpref";
                
                /// <summary> Path to Content/Assets/Prefast/Tombstone.wpref </summary>
                public const string Tombstone = "Content/Assets/Prefast/Tombstone.wpref";
            }
        }
        
        public sealed class Fonts
        {
            
            /// <summary> Path to Content/Fonts/Playbill_48.TTF </summary>
            public const string Playbill_48_TTF = "Content/Fonts/Playbill_48.TTF";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
